project:
  type: website

website:
  title: "Lauren Pettit's Math 378 Final Project"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lab 1 Penguins EDA"
        href: web-eda.qmd
      - text: "Lab 1 Model"
        href: web-model.qmd
        

format:
  html:
    theme: cyborg 
    css: styles.css
    toc: true

editor: visual
